tests-stable-backports:
  stage: test
  image: debian:stable-backports
  script:
    - apt-get update
    - apt-get build-dep -y .
    - dpkg-buildpackage -us -uc -tc

tests-testing:
  stage: test
  image: debian:testing
  script:
    - apt-get update
    - apt-get build-dep -y .
    - dpkg-buildpackage -us -uc -tc

tests-unstable-all:
  stage: test
  image: debian:unstable
  script:
    - apt-get update
    - apt-get build-dep -y -Ppkg.debhelper.ci .
    - dpkg-buildpackage -us -uc -tc

tests-unstable:
  stage: test
  image: debian:unstable
  script:
    - apt-get update
    - apt-get build-dep -y .
    - dpkg-buildpackage -us -uc -tc

include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml

autopkgtest-more:
    extends: .test-autopkgtest
    before_script:
      - apt-get update
      - apt-get install -y libtest-pod-perl bmake dh-golang
